[default]
proxy = ""
watch_dir = "~/rtorrent/watch/start"
fast_upload = false
snapshots = true
snapshot_columns = 3
snapshot_rows = 2
snapshot_row_width = 1000 # will be lowered if it's higher than the site's width for the torrent page

# Image uploaders
[img_uploaders]
keksh_api_key = "" # will be used if provided for higher image size
ptpimg_api_key = "" # required if uploader is "ptpimg"

# Site credentials and settings
# Credentials below are required unless you uses cookies instead.
[avistaz]
username = ""
password = ""
totp_secret = ""
anonymous_upload = true
2captcha_api_key = ""
# proxy = "http://user:pass@example.com:6060"

[broadcasthenet]
username = ""
password = ""
img_uploader = "keksh"
totp_secret = ""
fasttorrent = true # set to false if <24 Mbps upload speed
# proxy = "http://user:pass@example.com:6060"

[hdbits]
username = ""
password = ""
img_uploader = "hdbimg"
totp_secret = ""
# proxy = "http://user:pass@example.com:6060"

[passthepopcorn]
username = ""
password = ""
passkey = "" # required for credential auth, auto-detected when using cookies
img_uploader = "ptpimg"
# personal_rip_tags = ["MYGRP"]
# proxy = "http://user:pass@example.com:6060"

[ncore]
username = ""
password = ""
img_uploader = "keksh"
totp_secret = ""
description = true # port, mafab, true, false
snapshot_rows = 3 # default is 3 suggested to not use more
anonymous_upload = false # default is false
# proxy = "http://user:pass@example.com:6060"
